site_name: TerraSky-Twilio
theme:
      name: readthedocs
      language: ja
markdown_extensions:
    - admonition
nav:
    - index.md
    - packageInstall.md
    - twilioSetting.md
    - afterInstallSetting.md
    - processBuilder.md
    - smsLogs.md

